name: kubera
description: A gold rewards and utility app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^13.0.0
  http: ^1.2.1
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  provider: ^6.1.2
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  fl_chart: ^0.64.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.0.0
  firebase_core: ^2.30.0
  firebase_auth: ^4.18.0
  firebase_storage: ^11.6.4
  image_picker: ^1.0.7
  cloud_firestore: ^4.15.5
  flutter_riverpod: ^2.5.1
  google_mobile_ads: ^4.0.0
  confetti: ^0.7.0
  scratcher: ^2.3.0
  share_plus: ^7.2.1
  flutter_fortune_wheel: ^1.2.0
  url_launcher: ^6.2.5
  font_awesome_flutter: ^10.5.0
  shimmer: ^3.0.0
  google_fonts: ^6.2.1
  flutter_staggered_animations: ^1.0.0
  smooth_page_indicator: ^1.0.0
  flutter_animate: ^4.5.0  # For animations
  hooks_riverpod: ^2.5.1  # For state management (modern alternative to flutter_riverpod)
  flutter_spinkit: ^5.2.1  # For loading animations
  flutter_holo_date_picker: ^1.1.3  # For potential date-based features (e.g., streak tracking)
  flutter_vibrate: ^1.3.0  # For haptic feedback
  animated_text_kit: ^4.2.2
  particles_flutter: ^0.1.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cached_network_image: ^3.3.1
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/scratch_cards/
    - assets/json/
    - assets/avatar/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf